import { deriveOutcome, OUTCOME, OUTCOME_LABELS, validateReopenChange, compatibilityResult } from './lib/decision-engine.js';
import { loadDecisions, saveDecision, getDecision, deleteDecision, deleteAllDecisions, createBackupPayload, restoreBackupPayload } from './lib/storage.js';
import { exportDecisionSheet, exportBackup } from './lib/export.js';

const app = document.querySelector('#app');
const state = { screen: 'home', activeId: null, volatileDecision: null, dialog: null, message: '' };

const screenNames = { home:'Home', saved:'Salvate', data:'Dati' };

function uid(){ return crypto.randomUUID ? crypto.randomUUID() : `cc-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function now(){ return new Date().toISOString(); }
function esc(v=''){ return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function current(){ return state.activeId ? getDecision(state.activeId) : state.volatileDecision; }
function navigate(screen, id=null){ state.screen=screen; state.activeId=id; state.dialog=null; render(); requestAnimationFrame(()=>document.querySelector('main h1')?.focus()); }
function flash(message){ state.message=message; render(); setTimeout(()=>{ state.message=''; render(); },2200); }
function fmtDate(value){ return new Intl.DateTimeFormat('it',{dateStyle:'medium'}).format(new Date(value)); }
function momentProgress(n){ return `<div class="progress-wrap"><div class="progress-label"><span>Momento ${n} di 5</span><span>${['Compatibilità','Avanzamento','Nucleo','Blocco','Chiusura'][n-1]}</span></div><div class="progress">${[1,2,3,4,5].map(i=>`<span class="${i<n?'done':i===n?'current':''}"></span>`).join('')}</div></div>`; }

function shell(content,{nav=true}={}){
  return `<div class="app-shell ${nav?'with-nav':''}"><header class="topbar"><div class="brand">ClearChoice</div><div class="privacy-pill">● Solo su questo dispositivo</div></header><main id="main">${content}</main>${nav?bottomNav():''}${state.message?`<div class="toast" role="status">${esc(state.message)}</div>`:''}${state.dialog?dialogMarkup():''}</div>`;
}
function bottomNav(){ return `<nav class="bottom-nav" aria-label="Navigazione principale">${['home','saved','data'].map(x=>`<button data-nav="${x}" class="${state.screen===x?'active':''}" aria-current="${state.screen===x?'page':'false'}">${screenNames[x]}</button>`).join('')}</nav>`; }
function render(){
  const renderer = {home:renderHome,compatibility:renderCompatibility,advancement:renderAdvancement,criteria:renderCriteria,blocker:renderBlocker,final:renderFinal,saved:renderSaved,data:renderData,reopen:renderReopen}[state.screen] || renderHome;
  app.innerHTML = renderer(); bindGlobal(); renderer.bind?.();
}
function bindGlobal(){
  document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.nav)));
  document.querySelectorAll('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>{state.dialog=null;render();}));
}
function dialogMarkup(){
  const d=state.dialog;
  if(d.type==='delete') return `<div class="dialog-backdrop"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><h2 id="dialog-title">Eliminare questa decisione?</h2><p>Bozza, revisioni e scheda finale verranno cancellate da questo dispositivo.</p><div class="row"><button class="btn btn-danger" id="confirm-delete">Elimina definitivamente</button><button class="btn btn-secondary" data-close-dialog>Annulla</button></div></section></div>`;
  if(d.type==='delete-all') return `<div class="dialog-backdrop"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><h2 id="dialog-title">Eliminare tutti i dati locali?</h2><p>Questa azione non può essere annullata senza un backup.</p><label class="field"><span>Digita ELIMINA</span><input class="input" id="delete-confirm-text"></label><div class="row"><button class="btn btn-danger" id="confirm-delete-all">Elimina tutti i dati</button><button class="btn btn-secondary" data-close-dialog>Annulla</button></div></section></div>`;
  return '';
}

function renderHome(){
  const all=loadDecisions(); const drafts=all.filter(d=>d.status==='Draft').slice(0,2); const done=all.filter(d=>d.status==='Completed').slice(0,2);
  const list=(items,empty)=>items.length?items.map(decisionCard).join(''):`<div class="card muted empty"><p>${empty}</p></div>`;
  return shell(`<section class="hero"><div class="eyebrow">Chiusura decisionale</div><h1 tabindex="-1">Continuo a pensarci, ma non sto avanzando.</h1><p>Metti a fuoco ciò che mantiene aperta una scelta. ClearChoice non assegna punteggi e non decide al posto tuo.</p><button class="btn btn-primary" id="new-decision">Chiarisci una decisione</button><p class="small muted">I contenuti restano su questo dispositivo. Nessun account necessario.</p></section><h2 class="section-title">Bozze recenti</h2>${list(drafts,'Nessuna bozza aperta.')}<h2 class="section-title">Concluse recenti</h2>${list(done,'Nessuna decisione conclusa.')}`);
}
renderHome.bind=()=>{ document.querySelector('#new-decision')?.addEventListener('click',()=>{state.volatileDecision=newDecision();navigate('compatibility');}); bindDecisionCards(); };
function newDecision(){ return {id:null,title:'',category:'',status:'Draft',currentMoment:1,createdAt:now(),updatedAt:now(),compatibility:{},alternatives:[{id:uid(),label:'',viability:'plausible'},{id:uid(),label:'',viability:'plausible'}],advancementCheck:{changedTypes:[],newElement:'',repeatedElement:'',noSubstantialChange:false},criteria:[],blockerAssessment:{structureIsClear:true,information:{},futureCondition:{},externalSupport:{},tradeoff:{}},finalOutcome:null,revisions:[]}; }
function decisionCard(d){ return `<article class="card list-item"><div class="list-item-head"><div><strong>${esc(d.title)}</strong><div class="small muted">${d.status==='Draft'?`Bozza · Momento ${d.currentMoment} di 5`:esc(OUTCOME_LABELS[d.finalOutcome?.type]||'Conclusa')}</div></div><span class="status-badge ${d.status==='Completed'?'complete':''}">${d.status==='Draft'?'Bozza':'Conclusa'}</span></div><div class="small muted">Modificata ${fmtDate(d.updatedAt)}</div><div class="list-actions"><button class="btn btn-secondary" data-open="${d.id}">${d.status==='Draft'?'Riprendi':'Apri scheda'}</button><button class="btn btn-text" data-delete="${d.id}">Elimina</button></div></article>`; }
function bindDecisionCards(){ document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>{const d=getDecision(b.dataset.open);navigate(d.status==='Completed'?'final':momentScreen(d.currentMoment),d.id);})); document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>{state.dialog={type:'delete',id:b.dataset.delete};render();bindDialog();})); }
function momentScreen(n){ return ({1:'compatibility',2:'advancement',3:'criteria',4:'blocker',5:'final'})[n]||'compatibility'; }
function bindDialog(){ document.querySelector('#confirm-delete')?.addEventListener('click',()=>{deleteDecision(state.dialog.id);state.dialog=null;flash('Decisione eliminata.');}); document.querySelector('#confirm-delete-all')?.addEventListener('click',()=>{if(document.querySelector('#delete-confirm-text').value==='ELIMINA'){deleteAllDecisions();state.dialog=null;flash('Tutti i dati locali sono stati eliminati.');}}); }

function renderCompatibility(){ const d=current()||newDecision(); const c=d.compatibility||{}; const alts=d.alternatives||[]; return shell(`${sessionHeader('Compatibilità e formulazione')}${momentProgress(1)}<div id="errors"></div><section class="card"><h2>Prima di iniziare</h2><p class="muted">ClearChoice è per decisioni personali, non urgenti e non specialistiche. Finché questo controllo non è superato, nessun testo viene salvato.</p><div class="check-list">${[['individual','La decisione riguarda principalmente me.'],['nonUrgent','Non richiede una risposta immediata.'],['nonSensitive','Non riguarda un’emergenza o un ambito sensibile.'],['notExecutionOnly','Non ho già scelto: il problema è ancora decidere.'],['notSeekingRecommendation','Non sto cercando qualcuno che scelga al posto mio.']].map(([k,l])=>`<label class="choice"><input type="checkbox" data-compat="${k}" ${c[k]?'checked':''}><span>${l}</span></label>`).join('')}</div></section><section class="card"><label class="field"><span>Completa: “Devo scegliere se…”</span><input class="input" id="decision-title" maxlength="140" value="${esc(d.title)}" placeholder="es. frequentare il corso serale o quello online"></label><div class="stack" id="alternatives">${alts.map((a,i)=>altInput(a,i)).join('')}</div><button class="btn btn-secondary" id="add-alt" ${alts.length>=4?'disabled':''}>Aggiungi alternativa</button></section><div class="row"><button class="btn btn-primary" id="start-flow">Inizia il percorso</button><button class="btn btn-text" id="cancel-new">Annulla</button></div>`,{nav:false}); }
renderCompatibility.bind=()=>{
  const d=current()||state.volatileDecision;
  document.querySelectorAll('[data-compat]').forEach(x=>x.addEventListener('change',()=>d.compatibility[x.dataset.compat]=x.checked));
  document.querySelector('#decision-title').addEventListener('input',e=>d.title=e.target.value);
  bindAltInputs(d,false);
  document.querySelector('#add-alt').addEventListener('click',()=>{d.alternatives.push({id:uid(),label:'',viability:'plausible'});state.volatileDecision=d;render();});
  document.querySelector('#cancel-new').addEventListener('click',()=>{state.volatileDecision=null;navigate('home');});
  document.querySelector('#start-flow').addEventListener('click',()=>{
    const errors=[]; const comp=compatibilityResult(d.compatibility); if(!comp.compatible) errors.push(comp.reason);
    const labels=d.alternatives.map(a=>a.label.trim()).filter(Boolean); if(d.title.trim().length<8) errors.push('Formula la decisione in modo più concreto.'); if(labels.length<2) errors.push('Inserisci almeno due alternative concrete.'); if(new Set(labels.map(x=>x.toLowerCase())).size!==labels.length) errors.push('Le alternative devono essere distinte.');
    if(errors.length){showErrors(errors);return;} d.id=d.id||uid(); d.createdAt=d.createdAt||now(); d.currentMoment=2; d.compatibility.compatible=true; saveDecision(d); state.volatileDecision=null; navigate('advancement',d.id);
  });
};
function altInput(a,i){return `<div class="alt-row"><label class="field"><span>Alternativa ${String.fromCharCode(65+i)}</span><input class="input" data-alt="${a.id}" value="${esc(a.label)}" maxlength="100"></label><button class="icon-btn" data-remove-alt="${a.id}" aria-label="Rimuovi alternativa">×</button></div>`;}
function bindAltInputs(d,persist=true){document.querySelectorAll('[data-alt]').forEach(x=>x.addEventListener('input',()=>{d.alternatives.find(a=>a.id===x.dataset.alt).label=x.value;if(persist)saveDecision(d);}));document.querySelectorAll('[data-remove-alt]').forEach(x=>x.addEventListener('click',()=>{if(d.alternatives.length>2){d.alternatives=d.alternatives.filter(a=>a.id!==x.dataset.removeAlt);if(persist)saveDecision(d);else state.volatileDecision=d;render();}}));}
function showErrors(errors){const el=document.querySelector('#errors');el.innerHTML=`<div class="error-summary" tabindex="-1"><strong>Controlla questi punti</strong><ul>${errors.map(e=>`<li>${esc(e)}</li>`).join('')}</ul></div>`;el.focus();}
function sessionHeader(title){return `<div class="session-header"><button class="btn btn-text" id="back">← Indietro</button><h1 tabindex="-1">${title}</h1><button class="btn btn-text" id="save-exit">Salva ed esci</button></div>`;}
function bindSessionHeader(d,previous){document.querySelector('#back')?.addEventListener('click',()=>navigate(previous,d.id));document.querySelector('#save-exit')?.addEventListener('click',()=>{saveDecision(d);navigate('home');});}

function renderAdvancement(){const d=current();const a=d.advancementCheck||{};const types=['Un fatto o un’informazione','Una delle alternative','Ciò che considero importante','Una condizione esterna'];return shell(`${sessionHeader('Che cosa è cambiato davvero?')}${momentProgress(2)}<section class="card"><p>Dall’ultima volta che hai pensato a questa decisione, è cambiato:</p><div class="check-list">${types.map((t,i)=>`<label class="choice"><input type="checkbox" data-change-type="${i}" ${(a.changedTypes||[]).includes(i)?'checked':''}><span>${t}</span></label>`).join('')}<label class="choice"><input type="checkbox" id="no-change" ${a.noSubstantialChange?'checked':''}><span>Nulla di sostanziale</span></label></div></section><section class="card"><label class="field"><span>Elemento realmente nuovo</span><textarea class="input" id="new-element" maxlength="300" placeholder="Inserisci solo ciò che può cambiare la scelta.">${esc(a.newElement)}</textarea></label><label class="field"><span>Che cosa continua a ripetersi?</span><textarea class="input" id="repeated-element" maxlength="300">${esc(a.repeatedElement)}</textarea></label></section><button class="btn btn-primary" id="continue">Continua</button>`,{nav:false});}
renderAdvancement.bind=()=>{const d=current();bindSessionHeader(d,'compatibility');document.querySelectorAll('[data-change-type]').forEach(x=>x.addEventListener('change',()=>{const v=Number(x.dataset.changeType);const set=new Set(d.advancementCheck.changedTypes||[]);x.checked?set.add(v):set.delete(v);d.advancementCheck.changedTypes=[...set];if(x.checked)d.advancementCheck.noSubstantialChange=false;saveDecision(d);render();}));document.querySelector('#no-change').addEventListener('change',e=>{d.advancementCheck.noSubstantialChange=e.target.checked;if(e.target.checked)d.advancementCheck.changedTypes=[];saveDecision(d);render();});document.querySelector('#new-element').addEventListener('input',e=>{d.advancementCheck.newElement=e.target.value;saveDecision(d)});document.querySelector('#repeated-element').addEventListener('input',e=>{d.advancementCheck.repeatedElement=e.target.value;saveDecision(d)});document.querySelector('#continue').addEventListener('click',()=>{d.currentMoment=3;saveDecision(d);navigate('criteria',d.id);});};

function renderCriteria(){const d=current();return shell(`${sessionHeader('Che cosa conta davvero?')}${momentProgress(3)}<div id="errors"></div><section class="card"><p>Scegli fino a tre criteri. Una preferenza ammette compromessi; una condizione non negoziabile elimina le alternative incompatibili.</p><div class="stack">${(d.criteria||[]).map((c,i)=>criterionInput(c,i)).join('')}</div><button class="btn btn-secondary" id="add-criterion" ${d.criteria.length>=3?'disabled':''}>Aggiungi criterio</button></section><section class="card"><h2>Alternative ancora plausibili</h2>${d.alternatives.map(a=>`<label class="choice"><input type="checkbox" data-viable="${a.id}" ${a.viability!=='eliminated'?'checked':''}><span>${esc(a.label)}</span></label>`).join('')}</section><button class="btn btn-primary" id="to-blocker">Verifica il blocco</button>`,{nav:false});}
renderCriteria.bind=()=>{const d=current();bindSessionHeader(d,'advancement');document.querySelector('#add-criterion').addEventListener('click',()=>{if(d.criteria.length<3){d.criteria.push({id:uid(),label:'',type:'preference',conflict:false});saveDecision(d);render();}});document.querySelectorAll('[data-criterion-label]').forEach(x=>x.addEventListener('input',()=>{d.criteria.find(c=>c.id===x.dataset.criterionLabel).label=x.value;saveDecision(d);}));document.querySelectorAll('[data-criterion-type]').forEach(x=>x.addEventListener('change',()=>{d.criteria.find(c=>c.id===x.dataset.criterionType).type=x.value;saveDecision(d);}));document.querySelectorAll('[data-remove-criterion]').forEach(x=>x.addEventListener('click',()=>{d.criteria=d.criteria.filter(c=>c.id!==x.dataset.removeCriterion);saveDecision(d);render();}));document.querySelectorAll('[data-viable]').forEach(x=>x.addEventListener('change',()=>{d.alternatives.find(a=>a.id===x.dataset.viable).viability=x.checked?'plausible':'eliminated';saveDecision(d);}));document.querySelector('#to-blocker').addEventListener('click',()=>{const errors=[];const plausible=d.alternatives.filter(a=>a.viability!=='eliminated');if(d.criteria.length<1)errors.push('Definisci almeno un criterio.');if(d.criteria.some(c=>c.label.trim().length<3))errors.push('Dai un nome concreto a ogni criterio.');if(plausible.length<1)errors.push('Non puoi eliminare tutte le alternative.');if(errors.length){showErrors(errors);return;}d.blockerAssessment.structureIsClear=plausible.length>=2;d.currentMoment=4;saveDecision(d);navigate('blocker',d.id);});};
function criterionInput(c,i){return `<div class="criterion-row"><div class="split"><label class="field"><span>Criterio ${i+1}</span><input class="input" data-criterion-label="${c.id}" value="${esc(c.label)}" maxlength="80"></label><label class="field"><span>Tipo</span><select class="input" data-criterion-type="${c.id}"><option value="preference" ${c.type==='preference'?'selected':''}>Preferenza</option><option value="nonNegotiable" ${c.type==='nonNegotiable'?'selected':''}>Non negoziabile</option></select></label></div><button class="icon-btn" data-remove-criterion="${c.id}" aria-label="Rimuovi criterio">×</button></div>`;}

function renderBlocker(){const d=current();const b=d.blockerAssessment||{};return shell(`${sessionHeader('Che cosa impedisce di chiudere?')}${momentProgress(4)}<section class="card"><h2>1. Informazione specifica</h2><label class="field"><span>Domanda verificabile</span><input class="input" id="info-question" value="${esc(b.information?.question)}" placeholder="es. La presenza del venerdì è obbligatoria?"></label><div class="row"><label class="choice"><input type="checkbox" id="info-verifiable" ${b.information?.verifiable?'checked':''}><span>È verificabile</span></label><label class="choice"><input type="checkbox" id="info-changes" ${b.information?.changesDecision?'checked':''}><span>Una risposta diversa cambierebbe la scelta</span></label></div></section><section class="card"><h2>2. Condizione futura</h2><label class="field"><span>Evento o data osservabile</span><input class="input" id="future-text" value="${esc(b.futureCondition?.text)}" placeholder="es. Esito della selezione entro il 30 settembre"></label><label class="choice"><input type="checkbox" id="future-observable" ${b.futureCondition?.observable?'checked':''}><span>La condizione è concreta e osservabile</span></label></section><section class="card"><h2>3. Supporto esterno</h2><label class="field"><span>Che cosa deve essere chiarito con un’altra persona?</span><input class="input" id="support-purpose" value="${esc(b.externalSupport?.purpose)}"></label><label class="choice"><input type="checkbox" id="support-needed" ${b.externalSupport?.needed?'checked':''}><span>Serve davvero questo chiarimento</span></label><label class="choice"><input type="checkbox" id="support-delegates" ${b.externalSupport?.delegatesChoice?'checked':''}><span>Sto chiedendo all’altra persona di scegliere al posto mio</span></label></section><section class="card"><h2>4. Trade-off</h2><label class="field"><span>Che cosa protegge e sacrifica l’opzione A?</span><input class="input" id="trade-a" value="${esc(b.tradeoff?.sideA)}"></label><label class="field"><span>Che cosa protegge e sacrifica l’opzione B?</span><input class="input" id="trade-b" value="${esc(b.tradeoff?.sideB)}"></label><label class="choice"><input type="checkbox" id="trade-accepted" ${b.tradeoff?.accepted?'checked':''}><span>Ho compreso e accettato il trade-off</span></label></section><button class="btn btn-primary" id="derive">Vedi il tuo stato</button>`,{nav:false});}
renderBlocker.bind=()=>{const d=current();bindSessionHeader(d,'criteria');const b=d.blockerAssessment;b.information=b.information||{};b.futureCondition=b.futureCondition||{};b.externalSupport=b.externalSupport||{};b.tradeoff=b.tradeoff||{};const map=[['info-question',b.information,'question','input'],['info-verifiable',b.information,'verifiable','checked'],['info-changes',b.information,'changesDecision','checked'],['future-text',b.futureCondition,'text','input'],['future-observable',b.futureCondition,'observable','checked'],['support-purpose',b.externalSupport,'purpose','input'],['support-needed',b.externalSupport,'needed','checked'],['support-delegates',b.externalSupport,'delegatesChoice','checked'],['trade-a',b.tradeoff,'sideA','input'],['trade-b',b.tradeoff,'sideB','input'],['trade-accepted',b.tradeoff,'accepted','checked']];map.forEach(([id,obj,key,mode])=>document.querySelector('#'+id).addEventListener(mode==='checked'?'change':'input',e=>{obj[key]=mode==='checked'?e.target.checked:e.target.value;saveDecision(d);}));document.querySelector('#derive').addEventListener('click',()=>{const outcome=deriveOutcome(d);d.finalOutcome={...outcome,userConfirmed:false,confirmedAt:null};d.currentMoment=5;saveDecision(d);navigate('final',d.id);});};

const outcomeCopy={
 [OUTCOME.READY]:['Hai elementi sufficienti per scegliere.','Alternative e criteri sono chiari. Non è emerso altro che giustifichi la riapertura dell’analisi.'],
 [OUTCOME.INFORMATION]:['Prima di scegliere, ti serve una risposta precisa.','Questa informazione potrebbe cambiare concretamente le alternative o il criterio decisivo.'],
 [OUTCOME.STRUCTURE]:['La decisione non è ancora abbastanza definita.','Prima di confrontare le opzioni, serve ridurre le alternative o chiarire che cosa conta davvero.'],
 [OUTCOME.TRADEOFF]:['Il blocco non è una mancanza di informazioni.','Le alternative proteggono priorità diverse. Serve riconoscere quale rinuncia sei disposto ad accettare.'],
 [OUTCOME.DEFER]:['Non serve decidere oggi.','Ha senso riesaminare la scelta quando si verificherà una condizione precisa.'],
 [OUTCOME.SUPPORT]:['Un’altra analisi individuale non basta.','Serve chiarire un elemento con una persona coinvolta o competente, mantenendo la scelta sotto la tua responsabilità.'],
 [OUTCOME.OUT_OF_SCOPE]:['Questa decisione è fuori dal perimetro.','ClearChoice non può offrire il tipo di supporto necessario.'],
};
function renderFinal(){const d=current();if(!d?.finalOutcome)return shell('<h1 tabindex="-1">Nessun esito disponibile</h1>');const o=d.finalOutcome;const [title,body]=outcomeCopy[o.type]||[OUTCOME_LABELS[o.type],o.reason];return shell(`${sessionHeader('Stato della decisione')}${momentProgress(5)}<section class="result"><div class="eyebrow">${esc(OUTCOME_LABELS[o.type])}</div><h1 tabindex="-1">${esc(title)}</h1><p>${esc(body)}</p><h2>Evidenze</h2><ul class="evidence">${(o.evidence||[]).map(e=>`<li>${esc(e)}</li>`).join('')||'<li>Le evidenze derivano dalle informazioni inserite nella sessione.</li>'}</ul><p class="small muted">ClearChoice struttura il ragionamento. Non fornisce consulenza e non decide al posto tuo.</p></section><div class="row"><button class="btn btn-primary" id="confirm-final">${d.status==='Completed'?'Scheda confermata':'Conferma e chiudi'}</button><button class="btn btn-secondary" id="export-sheet">Esporta scheda</button><button class="btn btn-text" id="reopen">È cambiato qualcosa</button><button class="btn btn-text" id="not-me">Non mi rappresenta</button></div>`,{nav:false});}
renderFinal.bind=()=>{const d=current();bindSessionHeader(d,'blocker');document.querySelector('#confirm-final').addEventListener('click',()=>{d.finalOutcome.userConfirmed=true;d.finalOutcome.confirmedAt=now();d.status='Completed';saveDecision(d);flash('Decisione chiusa e salvata localmente.');});document.querySelector('#export-sheet').addEventListener('click',()=>{exportDecisionSheet(d);flash('Scheda esportata.');});document.querySelector('#reopen').addEventListener('click',()=>navigate('reopen',d.id));document.querySelector('#not-me').addEventListener('click',()=>{d.currentMoment=4;saveDecision(d);navigate('blocker',d.id);});};

function renderReopen(){const d=current();return shell(`${sessionHeader('È cambiato qualcosa?')}<section class="card"><p>Una decisione conclusa viene riaperta soltanto quando esiste un elemento concreto nuovo.</p><label class="field"><span>Tipo di cambiamento</span><select class="input" id="change-type"><option value="">Seleziona</option><option value="information">Nuova informazione</option><option value="alternative">Nuova alternativa</option><option value="criterion">Criterio cambiato</option><option value="condition">Condizione verificatasi</option><option value="tradeoff">Trade-off compreso diversamente</option></select></label><label class="field"><span>Che cosa è cambiato?</span><textarea class="input" id="change-summary" maxlength="300"></textarea></label><div id="errors"></div></section><button class="btn btn-primary" id="confirm-reopen">Riapri con questo cambiamento</button>`,{nav:false});}
renderReopen.bind=()=>{const d=current();bindSessionHeader(d,'final');document.querySelector('#confirm-reopen').addEventListener('click',()=>{const change={type:document.querySelector('#change-type').value,summary:document.querySelector('#change-summary').value};const v=validateReopenChange(change);if(!v.valid){showErrors([v.error]);return;}d.revisions=d.revisions||[];d.revisions.push({id:uid(),createdAt:now(),changedElementType:change.type,changedElementSummary:change.summary,previousOutcome:structuredClone(d.finalOutcome)});d.status='Draft';d.currentMoment=2;d.finalOutcome=null;d.advancementCheck={changedTypes:[],newElement:change.summary,repeatedElement:'',noSubstantialChange:false};saveDecision(d);navigate('advancement',d.id);});};

function renderSaved(){const all=loadDecisions();return shell(`<h1 tabindex="-1">Decisioni salvate</h1><p class="muted">Bozze e schede concluse restano soltanto su questo dispositivo.</p><label class="field"><span>Cerca</span><input class="input" id="search" placeholder="Cerca nelle decisioni"></label><div id="saved-list">${all.length?all.map(decisionCard).join(''):'<div class="card empty"><p>Non hai ancora salvato decisioni.</p></div>'}</div>`);}
renderSaved.bind=()=>{bindDecisionCards();document.querySelector('#search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();const filtered=loadDecisions().filter(d=>d.title.toLowerCase().includes(q));document.querySelector('#saved-list').innerHTML=filtered.length?filtered.map(decisionCard).join(''):'<div class="card empty"><p>Nessun risultato.</p></div>';bindDecisionCards();});};

function renderData(){const all=loadDecisions();return shell(`<h1 tabindex="-1">Dati e privacy</h1><section class="card"><h2>Solo su questo dispositivo</h2><p>Non serve un account e il funzionamento principale non invia contenuti a un server.</p><p><strong>${all.length}</strong> decisioni salvate localmente.</p></section><section class="card"><h2>Backup</h2><p class="muted">Il backup contiene tutte le decisioni e serve per ripristinarle su un dispositivo compatibile.</p><div class="row"><button class="btn btn-primary" id="backup">Crea backup</button><label class="btn btn-secondary" for="restore-file">Ripristina backup</label><input class="hidden" id="restore-file" type="file" accept="application/json"></div></section><section class="card"><h2>Cancellazione</h2><p class="muted">Puoi eliminare tutti i contenuti locali. Senza backup, l’azione è irreversibile.</p><button class="btn btn-danger" id="delete-all">Elimina tutti i dati</button></section><section class="card muted"><h2>Limiti</h2><p>ClearChoice non fornisce consulenza e non è adatta a decisioni urgenti, mediche, legali, fiscali, finanziarie ad alto impatto o relative alla sicurezza.</p></section>`);}
renderData.bind=()=>{document.querySelector('#backup').addEventListener('click',()=>{exportBackup(createBackupPayload());flash('Backup creato.');});document.querySelector('#restore-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const payload=JSON.parse(await file.text());const result=restoreBackupPayload(payload);result.valid?flash('Dati ripristinati.'):flash(result.error);}catch{flash('Backup non valido.');}});document.querySelector('#delete-all').addEventListener('click',()=>{state.dialog={type:'delete-all'};render();bindDialog();});};

render();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
